Host ailab
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  Compression yes
  ServerAliveInterval 30
  ServerAliveCountMax 3

  ControlMaster auto
  ControlPersist 10m
  ControlPath ~/.ssh/cm-%r@%h:%p

Host hdev
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY caijisong.caijisong+root.ailab-vlaflow.ws@h.pjlab.org.cn

Host hgpu2a
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY ws-d29e781d063ab421-worker-dw5pg.caijisong+root.ailab-vlaflow.pod@h.pjlab.org.cn


Host hgpu1a
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY ws-d29e781d063ab421-worker-h8grm.caijisong+root.ailab-vlaflow.pod@h.pjlab.org.cn


Host hgpu4a
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY ws-d29e781d063ab421-worker-hd8nh.caijisong+root.ailab-vlaflow.pod@h.pjlab.org.cn

Host 4090
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh root@123.57.187.96 -p 977
