Host ailab
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  Compression yes
  ServerAliveInterval 30
  ServerAliveCountMax 3

  ControlMaster auto
  ControlPersist 10m
  ControlPath ~/.ssh/cm-%r@%h:%p

Host mac
  HostName 10.6.7.40
  User happytech
  ProxyCommand none

  AddressFamily inet
  ConnectTimeout 5

  Compression yes
  ServerAliveInterval 30
  ServerAliveCountMax 3

  ControlMaster auto
  ControlPersist 10m
  ControlPath ~/.ssh/cm-%r@%h:%p
  
Host huawei
  HostName 124.71.175.237
  User root
  ProxyCommand none

  Compression yes
  ServerAliveInterval 30
  ServerAliveCountMax 3

  ControlMaster auto
  ControlPersist 10m
  ControlPath ~/.ssh/cm-%r@%h:%p
  
Host huawei-c
  HostName 1.94.176.66
  User root
  ProxyCommand none

  Compression yes
  ServerAliveInterval 30
  ServerAliveCountMax 3

  ControlMaster auto
  ControlPersist 10m
  ControlPath ~/.ssh/cm-%r@%h:%p
  
Host hdev
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY caijisong.caijisong+root.ailab-vlaflow.ws@h.pjlab.org.cn

Host hgpu2a
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY ws-d29e781d063ab421-worker-dw5pg.caijisong+root.ailab-vlaflow.pod@h.pjlab.org.cn


Host hgpu1a
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY ws-d29e781d063ab421-worker-h8grm.caijisong+root.ailab-vlaflow.pod@h.pjlab.org.cn


Host hgpu4a
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh -CAXY ws-d29e781d063ab421-worker-9hxhv.caijisong+root.ailab-vlaflow.pod@h.pjlab.org.cn

Host 4090a
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh root@123.57.187.96 -p 1004

Host a800
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force
  RemoteCommand ssh root@106.13.248.92 -p 4000

Host 4090b
  HostName 100.88.4.3
  User humanoid
  ProxyCommand none

  RequestTTY force

  RemoteCommand ssh root@123.57.187.96 -p 982
