{ pkgs, config, lib, ... }:
let
  paletteLuaPath = ".config/nvim/lua/stylix_palette.lua";
  fallbackColors = {
    base00 = "#1f1f28";
    base01 = "#2a2a37";
    base02 = "#223249";
    base03 = "#727169";
    base04 = "#c8c093";
    base05 = "#dcd7ba";
    base06 = "#938056";
    base07 = "#717c7c";
    base08 = "#c34043";
    base09 = "#ffa066";
    base0A = "#c0a36e";
    base0B = "#76946a";
    base0C = "#6a9589";
    base0D = "#7e9cd8";
    base0E = "#957fb8";
    base0F = "#d27e99";
  };
  colors = lib.attrByPath [ "lib" "stylix" "colors" "withHashtag" ] fallbackColors config;
in
{

  home.packages = with pkgs; [
    neovim
    lua-language-server
    stylua
    tree-sitter
    neovide
    lazygit
  ];
  home.file.${paletteLuaPath}.text = ''
    -- stylix_palette.lua · auto-generated by Stylix
    return {
      base00 = '${colors.base00}', base01 = '${colors.base01}',
      base02 = '${colors.base02}', base03 = '${colors.base03}',
      base04 = '${colors.base04}', base05 = '${colors.base05}',
      base06 = '${colors.base06}', base07 = '${colors.base07}',
      base08 = '${colors.base08}', base09 = '${colors.base09}',
      base0A = '${colors.base0A}', base0B = '${colors.base0B}',
      base0C = '${colors.base0C}', base0D = '${colors.base0D}',
      base0E = '${colors.base0E}', base0F = '${colors.base0F}',
    }
  '';
}
